version: "3"
services:
  frontend:
    image: httpd:latest
    ports:
      - "8080:80"
    volumes:
      - "./backoffice-front:/usr/local/apache2/htdocs/"
  backend:
    image: ggmartinez/laravel:9-php8-Xdebug
    ports:
      - "8081:8000"
    volumes:
      - "./backoffice-api:/app"
  database:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=laravel
    ports:
      - "3307:3306"
    volumes:
      - "./mysql:/var/lib/mysql"
    