version: "3"
services:
  frontend:
    image: httpd:latest
    ports:
      - "8080:80"
    volumes:
      - "./backoffice-front:/usr/local/apache2/htdocs/"
  backend:
    container_name: laravel
    tty: true
    restart: unless-stopped
    build:
      context: ./backoffice-backend
      dockerfile: Dockerfile
    volumes:
      - ./backoffice-backend:/backoffice-backend
    ports:
      - "8000:80"
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=database
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=1234
    depends_on:
      - db
  db:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=laravel
    ports:
      - "3306:3306"
    volumes:
      - "./mysql:/var/lib/mysql"
    