version: "3"
services:
  frontend:
    image: httpd:latest
    ports:
      - "8080:80"
    volumes:
      - "./backoffice-front:/usr/local/apache2/htdocs/"
  backend:
    image: ggmartinez/laravel:8
    ports:
      - "8000:8000"
    volumes:
      - "./backoffice-backend:/app"
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=database
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=1234
    depends_on:
      - database
  database:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=laravel
    ports:
      - "3307:3306"
    volumes:
      - "./mysql:/var/lib/mysql"
    