version: "3"

services:

  frontend:
    container_name: backoffice-frontend
    image: marrzuy/backoffice-frontend:latest
    ports:
      - "8080:80"

  backend:
    container_name: backoffice-backend
    tty: true
    restart: unless-stopped
    image: marrzuy/backoffice-backend:latest
    volumes:
      - ./ENV:/var/www/html/.env
    ports:
      - "9000:80"
