version: "3"

services:

  frontend:
    container_name: backoffice-frontend
    image: marrzuy/backoffice-frontend:latest
    ports:
      - "8080:80"

  backend:
    container_name: backoffice-backend
    tty: true
    restart: unless-stopped
    image: marrzuy/backoffice-backend:latest
    volumes:
      - ./ENV:/var/www/html/.env
      - ./script.sh:/var/www/html/script.sh
      - ./optimize.sh:/var/www/html/optimize.sh
#    command: bash "script.sh && httpd -D FOREGROUND"
    ports:
      - "9000:80"
